services:
  mysql:
    container_name: 'producerdb'
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=producerdb'
      - 'MYSQL_PASSWORD=123'
      - 'MYSQL_ROOT_PASSWORD=123'
      - 'MYSQL_USER=admin'
    ports:
      - '3307:3306'

  rabbitmq:
    image: rabbitmq:3.8.6-management
    container_name: rabbitmq-masterdev
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: 123
    ports:
      - '5672:5672'
      - '15672:15672'
